print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("How much would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill? "))
final = round((bill * (1 + (tip/100))) / people ,2)
print("Each person should pay:", final ,"$")